spring.application.name=tideEmail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=tidemailserver@gmail.com
spring.mail.password=psug csvn oxgn titj
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
